export { default as EmptyChatIcon } from "./svgs/EmptyChat.svg";
export { default as MicOffIcon } from "./svgs/MicOff.svg";
export { default as MicOnIcon } from "./svgs/MicOn.svg";
export { default as VideoOffIcon } from "./svgs/VideoOff.svg";
export { default as VideoOnIcon } from "./svgs/VideoOn.svg";
export { default as ScreenShareIcon } from "./svgs/ScreenShare.svg"
export { default as ScreenShareStopIcon } from "./svgs/ScreenShareStop.svg"
export { default as ChatIcon } from "./svgs/Chat.svg"
export { default as SettingsIcon } from "./svgs/Settings.svg"
export { default as FullscreenExitIcon } from "./svgs/FullscreenExit.svg"
export { default as FullscreenEnterIcon } from "./svgs/FullscreenEnter.svg"
export { default as CallEndIcon } from "./svgs/CallEnd.svg"
export { default as CallStartIcon } from "./svgs/CallStart.svg"
export { default as RecordingIcon } from "./svgs/Recording.svg"
export { default as RecordButtonIcon } from "./svgs/RecordButton.svg"
export { default as AttachmentIcon } from "./svgs/Attachment.svg"
export { default as SendIcon } from "./svgs/Send.svg"
export { default as CloseButtonIcon } from "./svgs/CloseButton.svg"
export { default as CheckIcon } from "./svgs/Check.svg"
export { default as CalenderIcon } from "./svgs/Calender.svg"
